CREATE TABLE IF NOT EXISTS padres (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    face_id VARCHAR(255) UNIQUE NOT NULL,
    guarderia_id INTEGER REFERENCES guarderias(id) ON DELETE CASCADE,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
